
adolc_include_path = '/home/b45ch1/workspace/SOLVINDSUITE/Packages/ADOL-C/Src/ADOL-C-2.1.0/ADOL-C/src'
adolc_library_path = '/home/b45ch1/workspace/SOLVINDSUITE/Packages/ADOL-C/adolc_base/lib'

colpack_include_path = '/home/b45ch1/workspace/SOLVINDSUITE/Packages/ADOL-C/adolc_base/include'
colpack_library_path = '/home/b45ch1/workspace/SOLVINDSUITE/Packages/ADOL-C/adolc_base/lib'

LIBS		= ['adolc',
                'ColPack',
            ]
LIBPATH		= [
                adolc_library_path,
                colpack_library_path,
            ]
INCLUDEPATH	= [
            adolc_include_path,
            colpack_include_path,
            ]

env = Environment(
	CPPPATH = INCLUDEPATH,
	CXXFLAGS= "-ftemplate-depth-100 -Wall -O2",
	LIBPATH  =LIBPATH,
	LIBS = LIBS,
	RPATH = LIBPATH, #include information where shared libraries can be found to avoid errors like: "ImportError: libboost_python-gcc42-mt-1_34_1.so.1.34.1: cannot open shared object file: No such file or directory"
	SHLIBPREFIX="", #gets rid of lib prefix, i.e. get mylib.so instead of libmylib.so
)
Default('.')
my_executable = env.Program(target='test_adolc.exe', source=['test_adolc.cpp'])

