LIBS		= [
				'adolc',
			]
LIBPATH		= [
				'../../adolc-2.0.0/adolc/.libs',
			]
INCLUDEPATH	= [
				'../../adolc-2.0.0',
				'/data/walter/opt_software/boost_1_34_1',
			]


env = Environment(
	CPPPATH = INCLUDEPATH,
	CXXFLAGS= "-ftemplate-depth-100 -Wall -O2",
	LIBPATH  =LIBPATH,
	LIBS = LIBS,
	RPATH = LIBPATH, #include information where shared libraries can be found to avoid errors like: "ImportError: libboost_python-gcc42-mt-1_34_1.so.1.34.1: cannot open shared object file: No such file or directory"
	SHLIBPREFIX="", #gets rid of lib prefix, i.e. get mylib.so instead of libmylib.so
)
Default('.')
my_executable = env.Program(target='adolc.exe', source=['adolc.cpp'])

