Import('env')
Import('adolc_include_path')

colpack = env.SharedLibrary(target='_colpack',
    source=['src/py_sparse_adolc.cpp',
    'src/num_util.cpp',
    adolc_include_path +'/sparse/sparsedrivers.cpp',
    adolc_include_path +'/sparse/sparse_fo_rev.cpp',
    adolc_include_path +'/int_forward_s.c',
    adolc_include_path +'/int_forward_t.c',
    adolc_include_path +'/int_reverse_s.c',
    adolc_include_path +'/int_reverse_t.c',
    adolc_include_path +'/nonl_ind_forward_s.c',
    adolc_include_path +'/nonl_ind_forward_t.c',
    adolc_include_path +'/indopro_forward_s.c',
    adolc_include_path +'/indopro_forward_t.c',
])

 
