#!/bin/bash

export CC="gcc -m64"
export CXX="g++ -m64"
unset CPPFLAGS
unset CXXFLAGS
unset CFLAGS
unset LDFLAGS

make clean
if [ $? -eq 0 ] ; then
   INSTDIR="${HOME}/adolc_base"
   ./configure --prefix=${INSTDIR} --libdir=${INSTDIR}/lib64 "$@"
fi
if [ $? -eq 0 ] ; then
   make
fi
