#!/bin/bash

export CC="gcc -m32"
export CXX="g++ -m32"
unset CPPFLAGS
unset CXXFLAGS
unset CFLAGS
unset LDFLAGS

make clean
if [ $? -eq 0 ] ; then
   INSTDIR="${HOME}/adolc_base"
   ./configure --prefix=${INSTDIR} --libdir=${INSTDIR}/lib32 "$@"
fi
if [ $? -eq 0 ] ; then
   make
fi
